swagger: "2.0"
info:
  title: Myapi
  description: API description in Markdown.
  version: 1.0.0
hosts: api-gateway
basePath: /v1
schemes:
  - https

paths:
  /getuser/{userId}:
    get:
      summary: Returns a list of users.
      description: Optional extended description in Markdown.
      produces:
        - application/json
      parameters:
        - in : path
          name: userId
          required: true
          type: integer
          minimum: 1
          description: Parameter description in Markdown.
      responses:
        200:
          description: OK   
      x-amazon-apigateway-integration:
        responses:
          default:
            statusCode: 200
        requestParameters: 
          integration.request.path.userId: method.request.path.userId
        uri: "http://api.clexom.com:8000/getuser/{userId}"
        httpMethod: GET
        type: http

  /createuser:
    post:
      summary: Create the new users.
      description: Api will create the new user
      produces:
      - application/json
      parameters:
        - in : body
          name: newdata
          required: true
      responses:
        200:
          description: OK

      x-amazon-apigateway-integration:
        responses:
          default:
            statusCode: 200
        uri: "http://api.clexom.com:8000/createuser"
        httpMethod: POST
        type: http      
